# Generated by Django 3.2.5 on 2021-07-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('dni', models.PositiveIntegerField(verbose_name='DNI')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('sueldo', models.FloatField(verbose_name='Sueldo')),
                ('boleta_sueldo', models.PositiveIntegerField(verbose_name='Numero de boleta de sueldo')),
            ],
        ),
    ]
