# Generated by Django 3.2.5 on 2021-07-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='name',
            new_name='nombre',
        ),
    ]
