# Generated by Django 3.2.5 on 2021-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='boleta_sueldo',
            field=models.CharField(max_length=30, verbose_name='Numero de boleta de sueldo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=9, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sueldo',
            field=models.CharField(max_length=30, verbose_name='Sueldo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Telefono'),
        ),
    ]
