# Generated by Django 3.2.5 on 2021-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20211113_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='direccion',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='referente',
            field=models.CharField(default='', max_length=60, verbose_name='Referente'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='domicilio',
            field=models.ManyToManyField(to='clientes.Domicilio'),
        ),
    ]
