# Generated by Django 3.2.5 on 2021-09-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210821_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo',
            field=models.CharField(choices=[('garante', 'garante'), ('solicitante', 'solicitante')], default='solicitante', max_length=15),
        ),
    ]
