# Generated by Django 3.2.5 on 2021-09-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterUniqueTogether(
            name='clientes',
            unique_together={('dni', 'apellido')},
        ),
    ]
