# Generated by Django 3.2.5 on 2021-11-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20211113_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='clientes',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.domicilio'),
        ),
    ]
