# Generated by Django 3.2.5 on 2021-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20211114_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
