# Generated by Django 3.2.5 on 2021-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clientes_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='numero_cliente',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
