# Generated by Django 3.2.5 on 2022-01-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField(verbose_name='Total de la venta')),
                ('fecha', models.DateField(verbose_name='Fecha y hora de la venta')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Numero de cuenta')),
                ('saldo', models.FloatField(default=0, verbose_name='Saldo')),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('morosa', 'morosa'), ('cancelada', 'cancelada')], default='activa', max_length=20, verbose_name='Estado')),
                ('baja', models.BooleanField(default=False)),
                ('anticipo', models.FloatField(default=0)),
                ('metodo_pago', models.CharField(choices=[('CONTADO', 'CONTADO'), ('TARJETA', 'TARJETA')], default='contado', max_length=20)),
                ('refinanciada', models.BooleanField(default=False)),
                ('descuento', models.FloatField(default=0)),
                ('garante1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garante1', to='clientes.clientes')),
                ('garante2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garante2', to='clientes.clientes')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_solicitante', to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(default=0, verbose_name='Numero de cuota')),
                ('importe', models.FloatField(verbose_name='importe')),
                ('saldo', models.FloatField(verbose_name='saldo')),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('impaga', 'impaga'), ('pagada', 'pagada'), ('morosa', 'morosa')], default='impaga', max_length=20, verbose_name='Estado de la cuota')),
                ('vencida', models.BooleanField(default=False)),
                ('recargo', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('refinanciada', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentas')),
            ],
            options={
                'ordering': ('numero_cuota',),
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('CONTADO', 'CONTADO'), ('TARJETA', 'TARJETA')], default='contado', max_length=20)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuotas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('descuento', models.FloatField(default=0)),
                ('cantidad', models.IntegerField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
        ),
    ]
