# Generated by Django 3.2.5 on 2021-08-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garante', models.CharField(max_length=50, verbose_name='Garante')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Numero de cuenta')),
                ('saldo', models.FloatField(verbose_name='Saldo')),
                ('productos', models.CharField(max_length=200, verbose_name='Productos')),
                ('estado', models.CharField(default='activa', max_length=20, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField(verbose_name='importe')),
                ('saldo', models.FloatField(verbose_name='importe')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(default='impaga', max_length=20, verbose_name='Estado')),
                ('recargo', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentas')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuotas')),
            ],
        ),
    ]
