# Generated by Django 3.2.5 on 2021-08-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='numero_cuota',
            field=models.IntegerField(default=0, verbose_name='Numero de cuota'),
        ),
    ]
