# Generated by Django 3.2.5 on 2021-08-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuotas_numero_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
