# Generated by Django 3.2.5 on 2021-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_cuentas_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='saldo',
            field=models.FloatField(default=0, verbose_name='Saldo'),
        ),
    ]
