# Generated by Django 3.2.5 on 2021-09-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_tipo'),
        ('cuentas', '0006_auto_20210902_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas',
            name='productos',
        ),
        migrations.CreateModel(
            name='DetalleCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
        ),
    ]
