# Generated by Django 3.2.5 on 2021-09-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auto_20210906_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas',
            name='fecha_inicio',
        ),
    ]
