# Generated by Django 3.2.5 on 2021-09-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_remove_cuotas_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='anticipo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='metodo_pago',
            field=models.CharField(choices=[('contado', 'contado'), ('tarjeta', 'tarjeta')], default='contado', max_length=20),
        ),
    ]
