# Generated by Django 3.2.5 on 2021-09-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_tipo'),
        ('cuentas', '0009_auto_20210908_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='garante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garante', to='clientes.clientes'),
        ),
    ]
