# Generated by Django 3.2.5 on 2021-09-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_auto_20210908_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
    ]
