# Generated by Django 3.2.5 on 2021-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_alter_cuentas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
    ]
