# Generated by Django 3.2.5 on 2021-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_auto_20210908_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='vencida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('impaga', 'impaga'), ('pagada', 'pagada'), ('morosa', 'morosa')], default='impaga', max_length=20, verbose_name='Estado de la cuota'),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='saldo',
            field=models.FloatField(verbose_name='saldo'),
        ),
    ]
