# Generated by Django 3.2.5 on 2021-10-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_auto_20210917_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotas',
            options={'ordering': ('numero_cuota',)},
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='estado',
            field=models.CharField(choices=[('activa', 'activa'), ('morosa', 'morosa'), ('inactiva', 'inactiva'), ('pagada', 'pagada')], default='activa', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='importe',
            field=models.FloatField(verbose_name='Total de la venta'),
        ),
    ]
