# Generated by Django 3.2.5 on 2021-11-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_auto_20211001_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='refinanciada',
            field=models.BooleanField(default=False),
        ),
    ]
