# Generated by Django 3.2.5 on 2021-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(choices=[('ELECTRODOMESTICOS', 'Electrodomesticos'), ('INDUMENTARIA', 'Indumentaria')], max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
