# Generated by Django 3.2.5 on 2022-01-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('total', models.FloatField()),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(unique=True)),
                ('codigo_ref', models.CharField(max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.rubros')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('cantidad', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.ingresos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
        ),
    ]
