# Generated by Django 3.2.5 on 2021-09-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productos_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo_ref',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('ELECTRODOMESTICOS', 'ELECTRODOMESTICOS'), ('INDUMENTARIA', 'INDUMENTARIA'), ('BAZAR', 'BAZAR'), ('REGALERIA', 'REGALERIA')], max_length=30),
        ),
    ]
