# Generated by Django 3.2.5 on 2021-10-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_detalleingreso_ingresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleingreso',
            name='ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.ingresos'),
        ),
    ]
