# Generated by Django 3.2.5 on 2021-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_detalleingreso_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleingreso',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
