# Generated by Django 3.2.5 on 2021-10-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20211008_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
